# Generated by Django 3.0.2 on 2020-03-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
            ],
        ),
    ]
